[package]
name = "adventofcode2017"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
queues = "1.0.2"
trees = "0.4.2"
regex = "1.5.4"
counter = "0.5.2"
pathfinding = "3.0.8"
ring-algorithm = "0.4.0"
